"use client";

import { useState } from "react";
import { cn } from "@/lib/utils";

/**
 * robots.txt generator for AI crawlers. Toggle each known AI user-agent to allow
 * or block, add your sitemap, and copy or download a ready-to-use robots.txt.
 * Crawlers are labelled by what they actually do (citations vs training vs live
 * fetch) so the choice is informed. Pure client-side — no network, no persistence.
 */

type Purpose = "Citations" | "Training" | "Live fetch";

interface Crawler {
  agent: string;
  owner: string;
  purpose: Purpose;
  note: string;
}

/** Verified, well-documented AI user-agents (June 2026). */
const CRAWLERS: Crawler[] = [
  { agent: "OAI-SearchBot", owner: "OpenAI", purpose: "Citations", note: "Powers ChatGPT search results and citations." },
  { agent: "ChatGPT-User", owner: "OpenAI", purpose: "Live fetch", note: "Fetches a page when a user's prompt needs it live." },
  { agent: "GPTBot", owner: "OpenAI", purpose: "Training", note: "Crawls to train OpenAI models. Blocking it won't remove you from ChatGPT search." },
  { agent: "PerplexityBot", owner: "Perplexity", purpose: "Citations", note: "Indexes pages so Perplexity can cite them." },
  { agent: "Perplexity-User", owner: "Perplexity", purpose: "Live fetch", note: "Fetches a page to answer a specific user query." },
  { agent: "ClaudeBot", owner: "Anthropic", purpose: "Training", note: "Crawls to train Claude models." },
  { agent: "Claude-User", owner: "Anthropic", purpose: "Live fetch", note: "Fetches a page when a Claude user's request needs it." },
  { agent: "Google-Extended", owner: "Google", purpose: "Training", note: "Controls use in Gemini/Vertex training only — does NOT affect Google Search or AI Overviews." },
  { agent: "Bingbot", owner: "Microsoft", purpose: "Citations", note: "Powers Bing and Microsoft Copilot. Blocking it removes you from Bing entirely." },
  { agent: "Applebot-Extended", owner: "Apple", purpose: "Training", note: "Controls use of your content in Apple's AI training." },
  { agent: "CCBot", owner: "Common Crawl", purpose: "Training", note: "Builds the open dataset many AI models train on." },
  { agent: "Bytespider", owner: "ByteDance", purpose: "Training", note: "Aggressive training crawler; often blocked to manage server load." },
];

const PURPOSE_TONE: Record<Purpose, string> = {
  Citations: "text-ok",
  "Live fetch": "text-accent",
  Training: "text-muted",
};

function download(filename: string, text: string, mime: string) {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function RobotsTxtGenerator() {
  // Default: allow everything (the AEO-sound default — you want to be crawled).
  const [allow, setAllow] = useState<Record<string, boolean>>(
    Object.fromEntries(CRAWLERS.map((c) => [c.agent, true])),
  );
  const [sitemap, setSitemap] = useState("");
  const [copied, setCopied] = useState(false);

  const toggle = (agent: string) =>
    setAllow((prev) => ({ ...prev, [agent]: !prev[agent] }));
  const setAll = (value: boolean) =>
    setAllow(Object.fromEntries(CRAWLERS.map((c) => [c.agent, value])));

  const output = [
    "# robots.txt — generated by The AEO Canon",
    "# https://www.aeocanon.com/tools/robots-txt-generator-ai-crawlers",
    "",
    ...CRAWLERS.flatMap((c) => [
      `User-agent: ${c.agent}`,
      allow[c.agent] ? "Allow: /" : "Disallow: /",
      "",
    ]),
    ...(sitemap.trim() ? [`Sitemap: ${sitemap.trim()}`, ""] : []),
  ]
    .join("\n")
    .trimEnd();

  const copy = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1500);
  };

  const allowedCount = CRAWLERS.filter((c) => allow[c.agent]).length;

  return (
    <section className="border-line bg-panel not-prose my-9 rounded-2xl border p-6 font-sans">
      <div className="flex items-center justify-between gap-4">
        <p className="text-accent font-mono text-[10.5px] tracking-[0.1em] uppercase">
          robots.txt generator for AI crawlers
        </p>
        <p className="text-muted font-mono text-[12px]">
          {allowedCount}/{CRAWLERS.length} allowed
        </p>
      </div>
      <p className="text-ink-2 mt-2 text-[14.5px] leading-relaxed">
        Toggle each crawler to allow or block it. To be cited, you want the{" "}
        <span className="text-ok">Citations</span> bots allowed. Blocking{" "}
        <span className="text-muted">Training</span> bots is a rights choice — it
        won&apos;t improve or remove your citations.
      </p>

      <div className="mt-4 flex gap-2">
        <button
          type="button"
          onClick={() => setAll(true)}
          className="border-line-2 text-ink-2 hover:border-accent hover:text-accent rounded-lg border px-3 py-1.5 text-[12.5px] font-medium transition-colors"
        >
          Allow all
        </button>
        <button
          type="button"
          onClick={() => setAll(false)}
          className="border-line-2 text-ink-2 hover:border-accent hover:text-accent rounded-lg border px-3 py-1.5 text-[12.5px] font-medium transition-colors"
        >
          Block all
        </button>
      </div>

      <ul className="mt-4 flex flex-col gap-px">
        {CRAWLERS.map((c) => {
          const on = allow[c.agent];
          return (
            <li key={c.agent}>
              <label className="hover:bg-paper flex cursor-pointer items-start gap-3 rounded-lg px-2 py-2">
                <input
                  type="checkbox"
                  checked={on}
                  onChange={() => toggle(c.agent)}
                  className="accent-accent mt-0.5 size-4 shrink-0"
                />
                <span className="min-w-0">
                  <span className="text-ink font-mono text-[13.5px] font-medium">
                    {c.agent}
                  </span>
                  <span className="text-muted ml-2 text-[12px]">{c.owner}</span>
                  <span
                    className={cn(
                      "ml-2 font-mono text-[10px] tracking-[0.08em] uppercase",
                      PURPOSE_TONE[c.purpose],
                    )}
                  >
                    {c.purpose}
                  </span>
                  <span className="text-ink-2 mt-0.5 block text-[13px] leading-snug">
                    {c.note}
                  </span>
                </span>
              </label>
            </li>
          );
        })}
      </ul>

      <label className="text-muted mt-4 block font-mono text-[10.5px] tracking-[0.1em] uppercase">
        Sitemap URL (optional)
      </label>
      <input
        value={sitemap}
        onChange={(e) => setSitemap(e.target.value)}
        placeholder="https://example.com/sitemap.xml"
        className="border-line-2 bg-paper text-ink focus:border-accent mt-2 w-full rounded-xl border px-4 py-2.5 text-[14px] outline-none"
      />

      <pre className="border-line-2 bg-paper text-ink mt-5 overflow-x-auto rounded-xl border p-4 font-mono text-[12.5px] leading-relaxed">
        {output}
      </pre>

      <div className="mt-4 flex flex-wrap gap-3">
        <button
          type="button"
          onClick={copy}
          className="border-accent bg-accent-soft text-accent-2 hover:bg-accent hover:text-white inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-[13.5px] font-medium transition-colors"
        >
          {copied ? "Copied ✓" : "Copy robots.txt"}
        </button>
        <button
          type="button"
          onClick={() => download("robots.txt", output, "text/plain")}
          className="border-line-2 text-ink-2 hover:border-accent hover:text-accent inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-[13.5px] font-medium transition-colors"
        >
          <span aria-hidden>↓</span> Download
        </button>
      </div>

      <p className="text-muted mt-4 text-[12.5px] leading-relaxed">
        Place the file at the root of your domain (example.com/robots.txt).
        robots.txt is a public, voluntary standard — reputable crawlers honor it,
        but it isn&apos;t access control. Note: Google AI Overviews use Googlebot,
        which has no separate AI opt-out.
      </p>
    </section>
  );
}
